positive_words = [
    # 'legal',
    # 'defines',
    # 'adopts',
    # 'accepts',
    'recognizes',
    # 'regulates',
    # 'embraces',
    # 'implements',
    # 'establishes',
    # 'clarifies',
    'allows',
    # 'implemented',
    # 'regulated',
    # 'recognizes',
    'issues',
    'classifies',
    # 'considers',
    # 'qualifies'
    ]

negative_words = [
    # 'ban',
    'does not allow',
    'has forbidden',
    'restricts',
    # 'not accepted',
    # 'permitted',
    # 'prohibits',
    # 'illegal',
    'bans',
    # 'rejects',
    # 'blocks',
    # 'banned',
    # 'issues warning',
    # 'unregulated',
    # 'not regulated',
    # 'warning',
    # 'no legislation',
    # 'rejected',
    # 'forbids',
    # 'restricted',
    # 'prohibited',
    # 'against'
    ]


pragmatic_actions = '(cryptocurrencies OR blockchain regulation OR mining OR cryptocurrencies as property OR crypto assets OR stablecoins OR CBDCs OR tokens OR ICOs OR cryptocurrencies as security OR cryptocurrency trading OR Bitcoin OR blockchain OR Bitcoin as legal tender OR NFTs)'

# pragmatic_actions = '(cryptocurrencies OR blockchain OR bitcoin OR mining of cryptocurrencies OR digital assets OR central bank digital currency)'

# pragmatic_actions = '()'

# hq = "central bank security exchange commission"
# hq = 'blockchain regulation'
hq = 'regulation of cryptocurrencies'
# pragmatic_actions = ['cryptocurrency as money',
# 'blockchain regulation',
# 'regulation of cryptocurrencies',
# 'cryptocurrency as a financial product',
# 'blockchain regulatory framework',
# 'deealing with cryptocurrency'
# 'cryptocurrency as an asset',
# 'stable coins',
# 'central bank digital currencies',
# 'token offerings',
# 'initial coin offerings',
# 'cryptocurrency as security',
# 'mining of cryptocurrencies',
# 'trading of cryptocurrencies',
# 'to regulate cryptocurrencies'
# ]

# countries = [
#     'Singapore',
#     'Malta',
#     'Gibraltar',
#     'Switzerland',
#     'Hong Kong',
#     'Cyprus',
#     'Greece',
#     'France',
#     'China',
#     'South Africa',
#     'Algeria',
#     'Egypt',
#     'Morocco',
#     'Nepal',
#     'Taiwan'


# ]

friendly_hostile = [
    'Hong Kong',
    'Singapore',
    'Gibraltar',
    'Malta',
    'Switzerland',
    'USA',
    'UK',
    'Nigeria',
    'El Salvador',
    'Estonia',
    'Iceland',
    'Cayman Islands',
    'Kenya',
    'Bolivia',
    'Egypt',
    'Morocco',
    'Bangladesh',
    'Nepal',
    'Tunisia',
    'Algeria'
]

eu_countries= [
    'Austria',
    'Belgium',
    'Bulgaria', 
    'Croatia', 
    'Cyprus', 
    'Czech Republic', 
    'Denmark', 
    'Estonia', 
    'Finland', 
    'France', 
    'Germany', 
    'Greece', 
    'Hungary', 
    'Ireland', 
    'Italy', 
    'Latvia', 
    'Lithuania', 
    'Luxembourg', 
    'Malta', 
    'Netherlands', 
    'Poland', 
    'Portugal', 
    'Romania', 
    'Slovakia', 
    'Slovenia', 
    'Spain',
    'Sweden'
]

countries = [
'USA',
'AFGHANISTAN',
'ALBANIA',
'ALGERIA',
'ANDORRA',
'ANGOLA',
'ANTIGUA and BARBUDA',
'ARGENTINA',
'ARMENIA',
'AUSTRALIA',
'AUSTRIA',
'AZERBAIJAN',
'BAHAMAS',
'BAHRAIN',
'BANGLADESH',
'BARBADOS',
'BELARUS',
'BELGIUM',
'BELIZE',
'BENIN',
'BERMUDAS',
'BHUTAN',
'BOLIVIA',
'BOSNIA',
'BOTSWANA',
'BRAZIL',
'BRUNEI',
'BULGARIA',
'BURKINA FASO',
'BURUNDI',
'CAMBODIA',
'CAMEROON',
'CANADA',
'CAPE VERDE',
'CAYMAN ISLANDS',
'CHILE',
'CHINA', 
'COLOMBIA',
'COMOROS',
'DEMOCRATIC REPUBLIC OF CONGO',
'REPUBLIC OF CONGO',
'COSTA RICA',
"COTE d' IVOIRE",
'CROATIA',
'CUBA',
'CYPRUS',
'CZECH REPUBLIC',
'DENMARK',
'DJIBOUTI',
'DOMINICA',
'DOMINICAN REPUBLIC',
'ECUADOR',
'EGYPT',
'EL SALVADOR',
'EQUATORIAL GUINEA',
'ERITREA',
'ESTONIA',
'ESWATINI',
'ETHIOPIA',
'FIJI',
'FINLAND',
'FRANCE',
'GABON',
'GAMBIA',
'GEORGIA',
'GERMANY',
'GHANA',
'GIBRALTAR',
'GREECE',
'GRENADA',
'GUATEMALA',
'GUINEA',
'GUINEA-BISSAU',
'GUYANA',
'HAITI',
'HONG KONG',
'HONDURAS',
'HUNGARY',
'ICELAND',
'INDIA',
'INDONESIA',
'IRAN',
'IRAQ',
'IRELAND',
'ISRAEL',
'ITALY',
'JAMAICA',
'JAPAN',
'JORDAN',
'KAZAKHSTAN',
'KENYA',
'KIRIBATI',
'SOUTH KOREA',
'KUWAIT',
'KYRGYZSTAN',
'LAOS',
'LATVIA',
'LEBANON',
'LESOTHO',
'LIBERIA',
'LIBYA',
'LIECHTENSTEIN',
'LITHUANIA',
'LUXEMBOURG',
'MADAGASCAR',
'MALAWI',
'MALAYSIA',
'MALDIVES',
'MALI',
'MALTA',
'MARSHALL ISLANDS',
'MAURITANIA',
'MAURITIUS',
'MEXICO',
'MICRONESIA',
'MOLDOVA',
'MONACO',
'MONGOLIA',
'MONTENEGRO',
'MOROCCO',
'MOZAMBIQUE',
'MYANMAR',
'NAMIBIA',
'NAURU',
'NEPAL',
'NETHERLANDS',
'NEW ZEALAND',
'NICARAGUA',
'NIGER', 
'NIGERIA',
'NORTH MACEDONIA',
'NORWAY',
'OMAN',
'PAKISTAN',
'PANAMA',
'PAPUA NEW GUINEA',
'PARAGUAY',
'PERU',
'PHILIPPINES',
'POLAND',
'PORTUGAL',
'QATAR',
'ROMANIA',
'RUSSIA',
'RWANDA',
'SAINT KITTS AND NEVIS',
'SAINT LUCIA',
'SAINT VINCENT AND THE GRENADINES',
'SAMOA',
'SAN MARINO',
'SAO TOME AND PRINCIPE',
'SAUDI ARABIA',
'SENEGAL',
'SERBIA',
'SEYCHELLES',
'SIERRA LEONE',
'SINGAPORE',
'SLOVAKIA',
'SLOVENIA',
'SOLOMON ISLANDS',
'SOMALIA',
'SOUTH AFRICA',
'SPAIN',
'SRI LANKA',
'SUDAN',
'SOUTH SUDAN',
'SURINAME',
'SWEDEN',
'SWITZERLAND',
'SYRIA',
'TAIWAN',
'TAJIKISTAN',
'TANZANIA',
'THAILAND',
'TOGO',
'TONGA',
'TUNISIA',
'TURKEY',
'TURKMENISTAN',
'TUVALU',
'UAE',
'UGANDA',
'UK',
'UKRAINE',
'URUGUAY',
'UZBEKISTAN',
'VANUATU',
'VENEZUELA',
'VIETNAM',
'YEMEN',
'ZAMBIA',
'ZIMBABWE',
'TRINIDAD AND TOBAGO',
'CURACAO',
]